### ISSUE TITLE
Did anybody encounter a problem when running the example trace?

### ISSUE THREAD

**Issue by putao1** [mesarpe/socialccnsim#1]
when I exectute

> python -O socialccnsim.py 2 lce facebook abilene lru exampletrace/verysmall

it display as follows(on Ubuntu 14):
Traceback (most recent call last):
  File "socialccnsim.py", line 363, in <module>
    executor = Executor(G, petersen, CACHE_SIZE, CACHING_STRATEGY, CACHE_STRUCTURE, SEQUENCE_FILE, MOBILITY_ENABLED, STEP_PRINTING, topology_file=TOPOLOGY_GRAPH)
  File "socialccnsim.py", line 115, in **init**
    self.initialize_catalog()
  File "socialccnsim.py", line 169, in initialize_catalog
    self.f = tempfile.NamedTemporaryFile(delete=True, dir='/data/tmp/')
  File "/usr/lib/python2.7/tempfile.py", line 462, in NamedTemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python2.7/tempfile.py", line 239, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 2] No such file or directory: '/data/tmp/tmpwtYJBg'
Exception AttributeError: "'Executor' object has no attribute 'conn'" in <bound method Executor.__del__ of <**main**.Executor object at 0x7f4c41d0db10>> ignored

**Comment by LydiaNosali** [comment]
I also had this error:
Traceback (most recent call last):
  File "socialccnsim.py", line 409, in <module>
    executor.run()
  File "socialccnsim.py", line 182, in run
    self.sched.run()
  File "/usr/lib/python2.7/sched.py", line 117, in run
    action(*argument)
  File "socialccnsim.py", line 253, in consume_from_server
    path = self.topology_nodes.get_path(social_issuer, row[1])
  File "/socialccnsim/topology_manager.py", line 103, in get_path
    return self.paths.calculate_path(self.topology_nodes[social_src], self.topology_nodes[social_dst])
KeyError: 1
