### ISSUE TITLE
problem when running trace 

### ISSUE THREAD

**Issue by moh1984** [mesarpe/socialccnsim#3]
if a trace with more than 10 user, I get this error

Traceback (most recent call last):
  File "socialccnsim.py", line 409, in <module>
    executor.run()
  File "socialccnsim.py", line 182, in run
    self.sched.run()
  File "/usr/lib/python2.7/sched.py", line 117, in run
    action(*argument)
  File "socialccnsim.py", line 253, in consume_from_server
    path = self.topology_nodes.get_path(social_issuer, row[1])
  File "/home/moh/socialccnsim1/topology_manager.py", line 103, in get_path
    return self.paths.calculate_path(self.topology_nodes[social_src], self.topology_nodes[social_dst])
KeyError: 18

**Comment by moh1984** [comment]
the problem is solved
